# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Operant
tagline:          'BA for Everyone'
description:      'Behavior Analysis for everyone.'
url:              http://operant.xyz
baseurl:          /

author:
  name:           'Travis Jones'
  url:            https://twitter.com/travjones0

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/operantxyz/operantxyz.github.io
